package org.protege.owl.codegeneration;

public enum CodeGenerationPhase {
	CREATE_INTERFACE_HEADER("interface.header"),
	CREATE_INTERFACE_ENUMCLASS("interface.enumclass"),
	CREATE_INTERFACE_ENUMTAIL("interface.enumtail"),
	CREATE_OBJECT_PROPERTY_INTERFACE("interface.object.property"),
	CREATE_FUNCTIONAL_OBJECT_PROPERTY_INTERFACE("interface.functional.object.property"),
	CREATE_DATA_PROPERTY_INTERFACE("interface.data.property"),
	CREATE_FUNCTIONAL_DATA_PROPERTY_INTERFACE("interface.functional.data.property"),
	CREATE_INTERFACE_TAIL("interface.tail"),
	CREATE_IMPLEMENTATION_HEADER("implementation.header"),
	CREATE_OBJECT_PROPERTY_IMPLEMENTATION("implementation.object.property"),
	CREATE_FUNCTIONAL_OBJECT_PROPERTY_IMPLEMENTATION("implementation.functional.object.property"),
	CREATE_DATA_PROPERTY_IMPLEMENTATION("implementation.data.property"),
	CREATE_FUNCTIONAL_DATA_PROPERTY_IMPLEMENTATION("implementation.functional.data.property"),
	CREATE_IMPLEMENTATION_TAIL("implementation.tail"),
	CREATE_POJO_HEADER("pojo.header"),
	CREATE_OBJECT_PROPERTY_POJO("pojo.object.property"),
	CREATE_DATA_PROPERTY_POJO("pojo.data.property"),
	CREATE_FUNCTIONAL_OBJECT_PROPERTY_POJO("pojo.functional.object.property"),
	CREATE_FUNCTIONAL_DATA_PROPERTY_POJO("pojo.functional.data.property"),
	CREATE_POJO_TAIL("pojo.tail"),
	CREATE_RSPOJO_HEADER("rspojo.header"),
	CREATE_RSPOJO_TAIL("rspojo.tail"),
	CREATE_RDFPOJO_HEADER("rdfpojo.header"),
	CREATE_OBJECT_PROPERTY_RDFPOJO("rdfpojo.object.property"),
	CREATE_DATA_PROPERTY_RDFPOJO("rdfpojo.data.property"),
	CREATE_FUNCTIONAL_OBJECT_PROPERTY_RDFPOJO("rdfpojo.functional.object.property"),
	CREATE_FUNCTIONAL_DATA_PROPERTY_RDFPOJO("rdfpojo.functional.data.property"),
	CREATE_RDFPOJO_TAIL("rdfpojo.tail"),
	CREATE_MODELPOJO_HEADER("modelpojo.header"),
	CREATE_OBJECT_PROPERTY_MODELPOJO("modelpojo.object.property"),
	CREATE_DATA_PROPERTY_MODELPOJO("modelpojo.data.property"),
	CREATE_INTDATA_PROPERTY_MODELPOJO("modelpojo.intdata.property"),
	CREATE_STRINGDATA_PROPERTY_MODELPOJO("modelpojo.stringdata.property"),
	CREATE_TYPEDDATA_PROPERTY_MODELPOJO("modelpojo.typeddata.property"),
	CREATE_FUNCTIONAL_OBJECT_PROPERTY_MODELPOJO("modelpojo.functional.object.property"),
	CREATE_FUNCTIONAL_DATA_PROPERTY_MODELPOJO("modelpojo.functional.data.property"),
	CREATE_MODELPOJO_TAIL("modelpojo.tail"),
	CREATE_MANAGERPOJO_HEADER("managerpojo.header"),
	CREATE_MANAGERPOJO_ENUM("managerpojo.enum"),
	CREATE_MANAGERPOJO_TAIL("managerpojo.tail"),
	CREATE_STORAGEMGT_HEADER("storagemgt.head"),
	CREATE_CLASS_STORAGEMGT("storagemgt.owlclass"),
	CREATE_ENUMCLASS_STORAGEMGT("storagemgt.enumclass"),
	//CREATE_OBJECT_PROPERTY_STORAGEMGT("storagemgt.object.property"),
	//CREATE_DATA_PROPERTY_STORAGEMGT("storagemgt.data.property"),
	CREATE_STORAGEMGT_ENUMTAIL("storagemgt.enumtail"),
	CREATE_STORAGEMGT_TAIL("storagemgt.tail"),
	CREATE_SERIALIZERMGT_HEADER("serializermgt.head"),
	CREATE_CLASS_SERIALIZERMGT("serializermgt.owlclass"),
	CREATE_SERIALIZERMGT_TAIL("serializermgt.tail"),
	CREATE_VOCABULARY_HEADER("vocabulary.header"),
	CREATE_CLASS_VOCABULARY("vocabulary.owlclass"),
	CREATE_OBJECT_PROPERTY_VOCABULARY("vocabulary.object.property"),
	CREATE_DATA_PROPERTY_VOCABULARY("vocabulary.data.property"),
	CREATE_VOCABULARY_TAIL("vocabulary.tail"),
	CREATE_FACTORY_HEADER("factory.header"),
	CREATE_FACTORY_TAIL("factory.tail"),
	CREATE_FACTORY_CLASS("factory.owlclass"),
	CREATE_NAMESPACE_HEADER("namespace.header"),
	CREATE_CLASS_NAMESPACE("namespace.owlclass"),
	CREATE_NAMESPACE_TAIL("namespace.tail"),
	CREATE_APPCONFIG_HEADER("appconfig.header"),
	CREATE_CLASS_APPCONFIG("appconfig.owlclass"),
	CREATE_APPCONFIG_TAIL("appconfig.tail"),
	CREATE_SCHEMA_FILE("schema.json.filehead"),
	CREATE_SCHEMA_EOF("schema.json.filetail"),
	CREATE_SCHEMA_HEADER("schema.json.header"),
	CREATE_SCHEMA_TAIL("schema.json.tail"),
	CREATE_SCHEMA_CLASS("schema.json.owlclass"),
	CREATE_SCHEMA_DATA_PROPERTY("schema.json.data.property"),
	CREATE_SCHEMA_FUNCTIONAL_DATA_PROPERTY("schema.json.functional.data.property"),
	CREATE_SCHEMA_OBJECT_PROPERTY("schema.json.object.property"),
	CREATE_SCHEMA_FUNCTIONAL_OBJECT_PROPERTY("schema.json.functional.object.property"),
    CREATE_WRAPPEDINDIVIDUAL("WrappedIndividual.template"),
    CREATE_WRAPPEDINDIVIDUALPOJO("WrappedIndividualPojo.template"),
    CREATE_WRAPPEDINDIVIDUALRDF("WrappedIndividualRDF.template"),
    CREATE_RESTWRAPPEDINDIVIDUAL("RestWrappedIndividual.template"),
    CREATE_MODELWRAPPEDINDIVIDUAL("ModelWrappedIndividual.template"),
    CREATE_ENUMWRAPPEDINDIVIDUAL("EnumWrappedIndividual.template")
	;
	
	private String templateName;
	
	private CodeGenerationPhase(String templateName) {
		this.templateName = templateName;
	}
	
	public String getTemplateName() {
		return templateName;
	}
}
